# Generated by Django 5.0.3 on 2024-06-16 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategorySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_categories', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AssetRequestSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_requests', models.IntegerField()),
                ('pending_requests', models.IntegerField()),
                ('approved_requests', models.IntegerField()),
                ('rejected_requests', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AssetSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_assets', models.IntegerField()),
                ('allocated_assets', models.IntegerField()),
                ('unallocated_assets', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceRequestSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_requests', models.IntegerField()),
                ('pending_requests', models.IntegerField()),
                ('approved_requests', models.IntegerField()),
                ('rejected_requests', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProfileSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_profiles', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_category_summary', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.assetcategorysummary')),
                ('asset_request_summary', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.assetrequestsummary')),
                ('asset_summary', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.assetsummary')),
                ('maintenance_request_summary', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.maintenancerequestsummary')),
                ('profile_summary', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.profilesummary')),
            ],
        ),
    ]
