# Generated by Django 5.0.3 on 2024-05-15 11:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_resettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='resettoken',
            name='create_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resettoken',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
