# Generated by Django 5.0.3 on 2024-06-16 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_invitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationKeys',
            fields=[
                ('organization_id', models.CharField(max_length=512, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='cotuser',
            name='private_key',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='cotuser',
            name='public_key',
            field=models.BinaryField(),
        ),
        migrations.CreateModel(
            name='SymmetricKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=512)),
                ('contract', models.CharField(max_length=512)),
                ('organization_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.organizationkeys')),
            ],
        ),
    ]
